# Generated by Django 2.2.8 on 2020-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('lead_author', models.CharField(blank=True, max_length=50, null=True)),
                ('heading_0', models.CharField(default='', max_length=200)),
                ('cheading_0', models.CharField(default='', max_length=5000)),
                ('heading_1', models.CharField(default='', max_length=200)),
                ('cheading_1', models.CharField(default='', max_length=5000)),
                ('heading_2', models.CharField(default='', max_length=200)),
                ('cheading_2', models.CharField(default='', max_length=5000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/post/')),
                ('pub_date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
