# Generated by Django 2.2.8 on 2020-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=30)),
                ('query', models.CharField(default='', max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('total_amount', models.FloatField(default=0.0)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(max_length=150)),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_zode', models.CharField(max_length=10)),
                ('primary_mobile_no', models.CharField(max_length=15)),
                ('secondary_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='-', max_length=50)),
                ('subcategory', models.CharField(default='-', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='product/category/')),
                ('pub_date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
